# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40a0ea59795b370c36b16f08a2ee598c7759c9b1b41fab4b5924b58654d784c15c2d614f67c37cb2d4096ead5695787c7d60cacecffb3c9e9706afd9c5fcca24

test:
  secret_key_base: 7445d59601c38d651451679efe7b56d152d3adbbf68bff8b90630d9074c544ed46dfd13816d865f16fff4230664dbd9b919728948b85a1b99c9113578f30d8d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
